name: GOSY 
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  clippy_flutter: ^2.0.0-nullsafety.1
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6 
  flutter_rating_bar: ^4.0.1
  image_picker: ^0.8.7+4
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  intl: ^0.17.0
  url_launcher: ^6.1.10
  go_router: ^14.8.1
  app_links: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoGosy.png"


flutter:

 
  uses-material-design: true

  
